### ISSUE TITLE
Implement pressure units

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#1]
Looking to implement units of pressure (Pa, bar, atm, Torr, psi).

**Comment by maiquynhtruong** [comment]
Hi can I work on this?
One question, though. I don't think I can find what 'at' means. Is that a unit?

**Comment by Akash-Pardasani** [comment]
@mattgd Is anybody working on this? I've started with a bit

**Comment by maiquynhtruong** [comment]
I already wrote the code for most of the units. I just don't know if that 'at' is a valid unit cause I can't find anything on it.

**Comment by mattgd** [comment]
@maiquynhtruong Oops, disregard that. Just Pascal, Bar, Atmosphere, Torr, and Poud-force per square inch is good. Thank you!

**Comment by gdurga** [comment]
Isn't the technical atmosphere?
Just sent a PR with this conversions, @maiquynhtruong probably you can merge with your work :)

refs:
[pressure units](https://en.wikipedia.org/wiki/Pressure#Units)
[converunits](http://www.convertunits.com)

**Comment by maiquynhtruong** [comment]
I already made a PR

**Comment by mattgd** [comment]
Thanks, @maiquynhtruong! Implemented in PR #12 and merged with master.
