### ISSUE TITLE
Make code backward compatible with python2

### ISSUE THREAD

**Issue by pwnfoo** [mattgd/UnitConverter#14]
A lot of people have Python2 as their default python interpreter. Currently, the code fails to run on python2. Here is the stacktrace : 

<pre>
$ python unit_converter.py
Python unit converter by mattgd.
     
Units supported:
     Circle     : radians (r), degrees (d) 
     Temperature    : Celsius (c), Fahrenheit (f), and Kelvin (k) 
     Speed      : Kilometers/hour (kph), miles/hour (mph), knots(kt) .

[-] Example entries: 1.345/r/d, 33/f/c, 2/mph/kph

[*] Enter a value and units to convert from and to: 33/f/c
Traceback (most recent call last):
  File "unit_converter.py", line 295, in <module>
    number = input('\n[*] Enter a value and units to convert from and to: ')
  File "<string>", line 1, in <module>
NameError: name 'f' is not defined
</pre>

**Comment by pwnfoo** [comment]
Looks like the input() function is the culprit. In py3, `raw_input()` defaults to `input()` while in py2, it doesn't, and hence the NameError.

**Comment by shashankaryan** [comment]
Code is compatible with Python2 and Python3 as of commit 61480e5.
