### ISSUE TITLE
Implement additional units of force

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#17]
Below is a table from Wikipedia with units of force that can be clearly implemented using the module's current format.

![image](https://cloud.githubusercontent.com/assets/9063128/19401557/f6d52006-9229-11e6-9739-ecf65320927e.png)

**Comment by pv2k** [comment]
I will take this one

**Comment by mattgd** [comment]
@pv2k Great, thanks.

For anyone: still looking to implement kp and pdl units. Virtual bonus points for adding the new units to the README as well.

**Comment by AggarwalAditya** [comment]
I will take the kp and pdl units.

**Comment by mattgd** [comment]
Great! Thank you, @AggarwalAditya.
