### ISSUE TITLE
Add conversions for moles

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#19]
- Any number can be converted into moles, so just having a check for if the input contains "mol" in it before all of the method checks (before the "Check the rest of the conversion factors" comment in unit_converter.py) is fine.
- Essentially just a "moles" method that takes conversion factors of two different units.
- Use 6.022140857e23 for the Avogadro constant.

**Comment by 500swapnil** [comment]
Hi I am working on this project. I will be sending in the pull request in some time.

**Comment by mattgd** [comment]
Great! Thank you, @500swapnil.

**Comment by mridulg** [comment]
@mattgd Doing so will leave only 2 `split()` components instead of the actual 3, right? How does one handle that?

**Comment by mattgd** [comment]
@mridulg Very true.

Going to close this issue for now. It needs a lot of planning and may not even be all that useful.

**Comment by mridulg** [comment]
@mattgd Sure. Do let me know if there is anything I could probably help with.
