### ISSUE TITLE
Implement additional energy units

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#2]
- Implement energy units (Joule, BTU, Calorie)
- Implement power units (Watt, Horsepower)

**Comment by sachinkamath** [comment]
Hey @mattgd , can you assign this to me?

**Comment by jerold** [comment]
Posted a PR covering the following conversions: Watts / Volts / Amps / Ohms / Joules / Horsepower
https://github.com/mattgd/UnitConverter/pull/4

**Comment by mattgd** [comment]
Watts, Volts, Amps, Ohms, Joules, and Horsepower implemented by @jerold. Additionally looking to implement BTUs, and Calories (note for myself or anyone who wants to implement them).
