### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#22]
If anyone has any ideas for a logo, or would like to take a shot at creating one, feel free.

**Comment by qbunt** [comment]
Taking a stab at this one.

**Comment by mattgd** [comment]
@qbunt Awesome, thanks. Excited to see what you come up with.

**Comment by qbunt** [comment]
Have a look at https://github.com/mattgd/UnitConverter/pull/24 and let me know what you think.

**Comment by mattgd** [comment]
Looks great! Merged, but I also hid the .logos folder from the repo so that it doesn't get pulled with the rest of the files. Now being hosted externally.

**Comment by qbunt** [comment]
Sweet! Glad you dig it!
