### ISSUE TITLE
Implements better way to do function inverses

### ISSUE THREAD

**Issue by mattgd** [mattgd/UnitConverter#28]
For example, the following could be turned into one method just by having an "inverse' parameter.

The existing two methods:

```
# Newtons to Dynes (dyn)
def n_to_dyn(n):
    return n * 10 ^ 5


# Dynes to Newtons (n)
def dyn_to_n(dyn):
    return dyn * 0.00001  # Precision of 5 significant digits
```

could be turned into one:

```
# Newtons (N) and Dynes (dyn)
# Decimal value, boolean inverse
def n_dyn(value, inverse):
    if inverse:
        return value / (10 ^ 5)

    return value * 10 ^ 5
```

This would require a rewrite of the method selection function that would allow it to select the function that has both the `units_from` and `units_to` in the name, and then decide if it's `units_from_units_to` , in which case `inverse` should be false, or if not then `inverse` should be set to true. Implementing this will require a bunch of changes to multiple files.

**Comment by mattgd** [comment]
Even better, the conversion factor could probably be selected from an array, and then we could just use one method for most, if not all of the conversions.

**Comment by ibiBgOR** [comment]
I have not the exact code in my mind and sitting not on my laptop but maybe it should be possible to give that function two optional params (via reflection and the UNITS array) named n and dyn and with this the code could 'inject' one of the given param into the function.
There we could only check against None and decide which conversion to make.

_edit:_ but your idea with the factor sounds nice too. Maybe the UNITS array could be expanded or each converter file got a new sub array with conversion

_edit:_ got a great idea. Will work on this one and look how my idea works out. If you're alright with this.

**Comment by suvojit-0x55aa** [comment]
Can i work on this ??

**Comment by mattgd** [comment]
@shin-migami Go for it! Definitely interested to see the different ways we could go about doing this.

**Comment by ibiBgOR** [comment]
As the commit comments indicate my solution is ready as a pull request (#31)
@shin-migami : Please keep implementing would love to see your solution
