### ISSUE TITLE
Make codebase pycodestyle compliant

### ISSUE THREAD

**Issue by pwnfoo** [mattgd/UnitConverter#3]
Right now, there are a handful of changes that need to be done.

Check this out : 
![screenshot from 2016-10-14 10-37-38](https://cloud.githubusercontent.com/assets/9546091/19376444/84f07716-91fb-11e6-92c7-6b1a153c7a8b.png)

**Comment by JoanNgatia** [comment]
Hi.Does this mean making the code PEP8 compliant?

**Comment by mattgd** [comment]
@andela-jngatia I believe pycodestyle was just renamed from PEP8.

If either of you would like to make those changes, I'd be happy to merge a pull request for it. Otherwise, thank you. I can take a look and make those changes.

**Comment by pwnfoo** [comment]
@mattgd, I have made a PR (#5). Please review.
